# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0009_podcastepisode_explicit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='tip_last_payout',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='tip_last_payout_amount',
            field=models.PositiveIntegerField(default=0, help_text='Last tip payout value paid out in cents'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='tip_value',
            field=models.PositiveIntegerField(default=0, help_text='Unpaid tip value in cents'),
        ),
    ]
