# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20150901_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='force_disable_cdn',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='force_enable_cdn',
        ),
    ]
