# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20151218_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='stripe_payout_recipient',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
